service: serverless-template-gcp-nodejs

package:
  exclude:
    - node_modules/**

provider:
  name: google
  stage: ${env:SLS_STAGE}
  runtime: nodejs10
  region: ${env:GCP_REGION}
  project: ${env:GCP_PROJECT}
  # the path to the credentials file needs to be absolute
  credentials: keyfile.json

plugins:
  - serverless-plugin-typescript
  - serverless-google-cloudfunctions

functions:
  hello_world_http:
    handler: hello_world_http
    events:
      - http: http
  hello_world_pubsup:
    handler: hello_world_pubsup
    timeout: 300s
    environment:
      STORAGE_BUCKET: hello_world_bucket
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: 'projects/${self:provider.project, ""}/buckets/hello_world'

